rule run_tests:
    run:
        commands = [
        "python3 -m virtualenv integration_venv",
        "source integration_venv/bin/activate",
        "git clone https://github.com/InstituteforDiseaseModeling/emod-api.git",
        "pip install emod_api --index-url=https://sbuxton@idmod.org:@packages.idmod.org/api/pypi/pypi-staging/simple",
        "cd emod-api/tests \n python -m unittest",
        "rm -rf emod-api",
        "git clone --single-branch --branch dev-next https://github.com/InstituteforDiseaseModeling/emodpy.git",
        "pip install emodpy --index-url=https://packages.idmod.org/api/pypi/pypi-production/simple --force-reinstall --no-deps",
        "pip install pytest",
        "pip install dataclasses",
        "pip install keyring",
        "pip install keyrings.alt",
        "pip install bs4",
        "pip install idmtools_test --index-url=https://packages.idmod.org/api/pypi/pypi-production/simple",
        "pip install idmtools_platform_comps --index-url=https://packages.idmod.org/api/pypi/pypi-production/simple",
        "pip install idmtools_models --index-url=https://packages.idmod.org/api/pypi/pypi-production/simple",
        "cd emodpy/tests \n pytest test_download_from_bamboo.py",
        "pytest -s -m emod",
        "rm -rf emodpy",
        "deactivate"
        "rm -rf integration_venv"
        ]
        for c in commands:
            shell(c)
