from emod_api.utils.str_enum import StrEnum


class DistributionType(StrEnum):
    NOT_INITIALIZED = 'NOT_INITIALIZED'
    CONSTANT_DISTRIBUTION = 'CONSTANT_DISTRIBUTION'
    UNIFORM_DISTRIBUTION = 'UNIFORM_DISTRIBUTION'
    GAUSSIAN_DISTRIBUTION = 'GAUSSIAN_DISTRIBUTION'
    EXPONENTIAL_DISTRIBUTION = 'EXPONENTIAL_DISTRIBUTION'
    POISSON_DISTRIBUTION = 'POISSON_DISTRIBUTION'
    LOG_NORMAL_DISTRIBUTION = 'LOG_NORMAL_DISTRIBUTION'
    DUAL_CONSTANT_DISTRIBUTION = 'DUAL_CONSTANT_DISTRIBUTION'
    WEIBULL_DISTRIBUTION = 'WEIBULL_DISTRIBUTION'
    DUAL_EXPONENTIAL_DISTRIBUTION = 'DUAL_EXPONENTIAL_DISTRIBUTION'
    BIMODAL_DISTRIBUTION = 'BIMODAL_DISTRIBUTION'
