name: Build and install package

runs:
  using: "composite"
  steps:
    - name: Config github user
      run: |
        git config --global user.email "idm_bamboo_user@idmod.org"
        git config --global user.name "BambooUser-IDM"
      - name: Checkout sources
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
    - name: Install python pre-reqs
      run: |
        python -m pip install --upgrade pip
        pip install .[packaging]
      shell: bash
    - name: Run bump2version
      run: |
        bump2version patch --commit
      shell: bash
    - name: Build wheel and install 
      run: |
        python -m build --wheel
        pip install dist/*
      shell: bash
