name: Package and test on Ubuntu

on:
  push:
    branches-ignore:
      - 'main'

  pull_request:
    branches:
      - 'main'

  # Allows manual run from the Actions tab
  workflow_dispatch:

jobs:
  build_test_ubuntu:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '***SKIPBUILD***')"
    strategy:
      max-parallel: 2
      matrix:
        python-version: [ '3.9', '3.10' ]
    steps:
      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install snappy
        run: |
          sudo apt-get install libsnappy-dev
        shell: bash
      - name: Build and install package
        uses: ./.github/actions/build-install-package
      - name: Install test requirements
        run: |
          pip install .[tests]
      - name: Run unit tests
        run: |
          python -m unittest discover .
        working-directory: ./tests
